blank_issues_enabled: false
contact_links:
  - name: BanClass 文档
    url: https://banclass.365sites.top
    about: 如果使用中需要帮助，请访问官方文档
  - name: 讨论区
    url: https://github.com/BanClass-Team/BanClass/discussions/
    about: 使用中若遇到使用问题或有新点子新需求，请先在这里求助和征求意见。
